apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: vulnerables/web-dvwa
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: dvwa-service
spec:
  selector:
    app: dvwa
  ports:
  - port: 80
    targetPort: 80
