apiVersion: waf.arthurcgc.waf-operator/v1
kind: WafPlan
metadata:
  name: default
  namespace: frontend
spec:
  image: arthurcgc/modsecurity:dos
  description: "dos enabled waf plan"
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
